{{- if not .Values.clickhouse.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-clickhouse-auth
  namespace: {{ .Release.Namespace }}
stringData:
  password: {{ .Values.clickhouse.auth.password | quote }}
{{- end }}
